IF EXISTS (SELECT name
   FROM   sysobjects
   WHERE  name = 'otvaranje_poslovne_godine' AND type = 'P')
   DROP PROCEDURE [otvaranje_poslovne_godine]
GO
---------------------------------------------------------
--   Procedura za otvaranje poslovne godine
---------------------------------------------------------
CREATE PROCEDURE dbo.[otvaranje_poslovne_godine]
   @POSL_SIS_ID INT,
   @POSL_GOD_GOD char(4),
   @POSL_GOD_DAT_ID datetime,
   @ID INT OUTPUT
AS
  
  declare @POSL_GOD_ID INT,
		  @POSL_GOD_ID_NEW INT

  select top 1 @POSL_GOD_ID = POSL_GOD_ID from POSLOVNA_GODINA where @POSL_SIS_ID = POSL_SIS_ID order by POSL_GOD_ID desc;

  INSERT INTO POSLOVNA_GODINA values (@POSL_SIS_ID, @POSL_GOD_GOD, @POSL_GOD_DAT_ID, null, 0);

  select top 1 @POSL_GOD_ID_NEW = POSL_GOD_ID from POSLOVNA_GODINA order by POSL_GOD_ID desc;
	
  SET @ID = @POSL_GOD_ID_NEW;
	
  declare @ROB_KART_ID INT,
		  @MAG_ID INT,
		  @ROBA_ID INT,
		  @POSL_GOD_ID1 INT,
		  @ROB_KART_POC_KOL	NUMERIC(14,4),
		  @ROB_KART_POC_VRED NUMERIC(14,4),
		  @ROB_KART_PRUL_KOL NUMERIC(14,4),
		  @ROB_KART_PRUL_VRED NUMERIC(14,4),
		  @ROB_KART_PRIZ_KOL NUMERIC(14,4),
		  @ROB_KART_PRIZ_VRED NUMERIC(14,4),
		  @ROB_KART_UKKOL NUMERIC(14,4),
		  @ROB_KART_UKVRED NUMERIC(14,4),
		  @ROB_KART_CEBA NUMERIC(14,4)

	  DECLARE cursROBNA_KARTICA CURSOR FOR SELECT ROB_KART_ID, MAG_ID, ROBA_ID,
				POSL_GOD_ID, ROB_KART_POC_KOL, ROB_KART_POC_VRED, ROB_KART_PRUL_KOL, ROB_KART_PRUL_VRED,
				ROB_KART_PRIZ_KOL, ROB_KART_PRIZ_VRED, ROB_KART_UKKOL, ROB_KART_UKVRED, ROB_KART_CEBA
			FROM ROBNA_KARTICA WHERE @POSL_GOD_ID = POSL_GOD_ID

	 OPEN cursROBNA_KARTICA
	 FETCH NEXT FROM cursROBNA_KARTICA INTO @ROB_KART_ID , @MAG_ID, @ROBA_ID, @POSL_GOD_ID1, 
				@ROB_KART_POC_KOL, @ROB_KART_POC_VRED, @ROB_KART_PRUL_KOL, @ROB_KART_PRUL_VRED,
				@ROB_KART_PRIZ_KOL, @ROB_KART_PRIZ_VRED, @ROB_KART_UKKOL, @ROB_KART_UKVRED, @ROB_KART_CEBA
	 WHILE @@FETCH_STATUS = 0
	 BEGIN
		IF(@ROB_KART_UKKOL > 0)
		BEGIN
			INSERT INTO ROBNA_KARTICA VALUES (@MAG_ID, @ROBA_ID, @POSL_GOD_ID_NEW, @ROB_KART_UKKOL, @ROB_KART_UKVRED,
											0, 0, 0, 0, @ROB_KART_UKKOL, @ROB_KART_UKVRED, @ROB_KART_CEBA);
			DECLARE @ROB_KART_ID_NEW INT,
					@BROJ_ANALITIKA NUMERIC(5)
					
			SELECT TOP 1 @ROB_KART_ID_NEW = ROB_KART_ID FROM ROBNA_KARTICA ORDER BY ROB_KART_ID DESC;
			
				SELECT @BROJ_ANALITIKA = COUNT(*) 
				FROM ANALITIKA_MAGACINSKE_KARTICE
				WHERE ROB_KART_ID = @ROB_KART_ID

			 SET @BROJ_ANALITIKA = @BROJ_ANALITIKA + 1
			INSERT INTO ANALITIKA_MAGACINSKE_KARTICE VALUES(@ROB_KART_ID_NEW, @BROJ_ANALITIKA, 'U', @ROB_KART_UKKOL, @ROB_KART_CEBA, @ROB_KART_UKVRED, 'S');
		END
			FETCH NEXT FROM cursROBNA_KARTICA INTO @ROB_KART_ID , @MAG_ID, @ROBA_ID, @POSL_GOD_ID1,
				@ROB_KART_POC_KOL, @ROB_KART_POC_VRED, @ROB_KART_PRUL_KOL, @ROB_KART_PRUL_VRED,
				@ROB_KART_PRIZ_KOL, @ROB_KART_PRIZ_VRED, @ROB_KART_UKKOL, @ROB_KART_UKVRED, @ROB_KART_CEBA
	 END

	 CLOSE cursROBNA_KARTICA
	 DEALLOCATE cursROBNA_KARTICA
   
GO